### ISSUE TITLE
time to take decisions

### ISSUE THREAD

**Issue by meleu** [botolo78/RetroPie-Manager#11]
We have 3 events that bring us a moment of decisions:
1. @HerbFargus created a cool RetroPie module for RetroPie-Manager installation and it puts the manager at `/opt/retropie/supplementary/retropie-manager/` directory.
2. @HerbFargus made a Pull Request #10 that solves the hardcoded `/home/pi` paths problem but brings the root user issue.
3. I created the `rpmanager.sh`. It solves the root user problem but depends on the hardcoded path `/opt/retropie/supplementary/retropie-manager/`.

Do you see the circle closing? :-)

The decisions we must take are:
- the @HerbFargus Pull Request #10 will be merged? (solves the hardcoded `/home/pi` problem)
- my `rpmanager.sh` will be used to start/stop the RetroPie-Manager? (solves the root user problem)
- installing RetroPie-Manager will be made by the RetroPie module only? (solves the hardcoded  `/opt/retropie/supplementary/retropie-manager/` problem)

My answer is Yes for the three questions.

What about you guys?

**Comment by botolo78** [comment]
I'm ok with everything.

**Comment by botolo78** [comment]
btw do you have privileges to merge a pull request guys?

**Comment by meleu** [comment]
You gave it to us! :smiley:

**Comment by botolo78** [comment]
Ok then :+1: 
In my opinion you should move on in all the install procedure without my worthless contribution on the matter :smile:

**Comment by meleu** [comment]
Let's wait if @herbfargus has something to say. If he agrees, we commit these changes and then update the instructions in the README.md

**Comment by meleu** [comment]
Hey! I have just found a way to make a script know where it is! :smiley: 
It's as simple as `rpmanager_dir=$(dirname $0)`. Therefore, there is no need to a hardcoded path in `rpmanager.sh`.

**Comment by meleu** [comment]
Since rpmanager is no longer dependent on the hardcoded path, and the @HerbFargus PR were merged, there is no need for this question anymore. I'm closing it.
