### ISSUE TITLE
Header Logo: support for reverse-proxy url

### ISSUE THREAD

**Issue by anthonyhendrickson** [botolo78/RetroPie-Manager#18]
When putting the django application behind a reverse-proxy, all urls seem OK except the header logo, which still shows (by default) "http://\<host ip\>:\<django port\>/".

Resolved by simply interpolating the manager's home url, instead of `{{ SITE.domain }}`. i.e., `{% url 'manager:home' %}`

**Comment by meleu** [comment]
Fixed by #19
