### ISSUE TITLE
Create RetroPie module for install

### ISSUE THREAD

**Issue by HerbFargus** [botolo78/RetroPie-Manager#4]
I have a preliminary module (currently nonworking) here: https://github.com/HerbFargus/RetroPie-Setup/commit/eb42431cf45d16a5618b3d564b1cdca47c5645ff

A few thoughts

- makefile may need some tweaks or I can manually define what is installed and where in the module
- not sure if we want to add is as an option to the autostart module, or just start it as a service on boot (like when xboxdrv Is enabled for example) or if we want a manual toggle in the menu to turn it off and on. Either way it should be automated 
- if we're feeling really ambitious we could make the port dynamic and user editable too

**Comment by botolo78** [comment]
That's a script for the retropie-setup :+1: 
Great, I didn't think about it. You should create a temporary branch, add that script and a simple install.sh the end user can run with wget to download and copy your module in the retropie supplementary directory.

Can you expand your  thoughts please?

**Comment by meleu** [comment]
@HerbFargus 
> - makefile may need some tweaks or I can manually define what is installed and where in the module

I feel more confident dealing with shell scripts than makefiles.

> - not sure if we want to add is as an option to the autostart module, or just start it as a service on boot (like when xboxdrv Is enabled for example) or if we want a manual toggle in the menu to turn it off and on. Either way it should be automated

My vote is first implement the toggle option, later we can decide how it can be autostarted. And I agree, it should be automated. I'll try to work in your module next weekend. :+1:

**Comment by botolo78** [comment]
That's a go for me too :+1:

**Comment by meleu** [comment]
Do you guys know how to add an retropie module in es retropie menu? It's simple with shell scripts, but retropie modules aren't "standalone" scripts...
[ I posted this same question at RetroPie forum:
https://retropie.org.uk/forum/topic/2370/how-to-add-an-retropie-setup-scriptmodule-in-es-retropie-menu ]

**Comment by botolo78** [comment]
I did it to add a switch to attract mode script. In think I put the script into the directory and es add it to the menu. I you have problems I could check that image for you

**Comment by meleu** [comment]
@botolo78 as I said, RetroPie modules aren't regular "standalone" scripts. So it isn't that simple to add them to emulationstation RetroPie menu... But I think it's better to discuss it on my forum's post. ;-)

**Comment by botolo78** [comment]
My bad, sorry :smile:

**Comment by meleu** [comment]
@HerbFargus I've noticed that you put the retropie-manager.sh module on your RetroPie-Setup repository. I think it's better to manage the files related to RetroPie-Manager on it's own repository.

We can write an install.sh to put the module in the `.../scriptmodules/supplementary/`. What do you think?

**Comment by botolo78** [comment]
Or just have both

**Comment by meleu** [comment]
oh sorry. I've just realized that it's an "exp" installation module. It's not a "config" module. I'll try to work on a "config" module to let the user manage the RetroPie-manager.

**Comment by meleu** [comment]
@HerbFargus would you mind to rename your script to, let's say, `install-retropie-manager.sh`, or maybe `install-rp-manager.sh`?
Then we can name the config module as `retropie-manager.sh`.

**Comment by meleu** [comment]
well... I've wrote an initial module for RetroPie-Manager here: https://github.com/meleu/RetroPie-Manager/blob/retropie/rpmanager.sh
It looks like this:
![captura de tela de 2016-07-06 15-25-57](https://cloud.githubusercontent.com/assets/8508804/16629868/10a84836-438e-11e6-8e25-47262e9aab57.png)

Some considerations:

- The script must be placed at `~/RetroPie-Setup/scriptmodules/supplementary/`.
- It starts the RetroPie-Manager and put those log messages in the `.../RetroPie-Manager/logs/` directory, (logfiles are named with a convenient style). Then, this `logs` directory must exist.
- I wrote an really embryonic [install.sh](https://github.com/meleu/RetroPie-Manager/blob/retropie/install.sh) that simply puts the `rpmanager.sh` in the right place and create the `logs` directory if it doesn't exist.

Please, tell me what you think about it.

**Comment by HerbFargus** [comment]
I have created a retropie module that fits the standards and style guide of the RetroPie-Setup script

https://github.com/HerbFargus/RetroPie-Setup/blob/4b8570fa413e55aabe69317d93e9830e1313bb79/scriptmodules/supplementary/retropie-manager.sh

It installs the manager in `/opt/retropie/supplementary/retropie-manager`

And since it follows the standards for the setup script it can automatically be updated and removed.

I've chosen to enable it as a service on boot with `/etc/rc.local` like we do with xboxdrv as its something I see people having running in the background as they need it rather than starting and stopping the service on the fly. 

It also runs on both my pc and my pi.

**Comment by botolo78** [comment]
You guys are awesome :)
Since this is you domain I'll step down and let you sort it out.

**Comment by meleu** [comment]
@HerbFargus Although the RetroPie-Manager is lightweight, I think that start/stop on the fly is useful for raspi1 users (like me).

Do you guys think that it's useful to save those log messages? Maybe it's useful for debugging, but I'm not sure if the regular users need it.

**Comment by botolo78** [comment]
Debug logs are useful when you are changing something and it crashes.
I really don't expect users to mess around with the code

**Comment by HerbFargus** [comment]
Yeah adding a start stop shouldn't  be a problem. I think we can do without logs. If it becomes something we need then we can add it later.

**Comment by meleu** [comment]
@HerbFargus Please, hold on with your PR. I'm working on a script (not a RetroPie module) to start, stop, start with logs, and update the RetroPie-Manager.

I think it'll be usefull for the Linux noobs. They won't need those big commands to start/stop/etc. RetroPie-Manager. It'll be simpler just use: `./rpmanager --start`, `./rpmanager --start --log`, and so on...

I'll try to release it tomorrow morning (I work better when my wife and kids are sleeping :P ).

Just for curiosity: whats the use of the md_ret_files variable [here](https://github.com/HerbFargus/RetroPie-Setup/blob/botolo-retropie/scriptmodules/supplementary/retropie-manager.sh#L37)?

**Comment by HerbFargus** [comment]
If you want this included with RetroPie it has to follow the standards of the setup script or else it won't be included. 

If you want to have a separate installer for people who add it manually then feel free to do that.

That variable tells it to retain the installed files in the retropie-manager folder

**Comment by meleu** [comment]
It'll be included on this RetroPie-Manager repository. But yes, I follow the RetroPie coding style.
I'm not talking about a separate installer, yours are perfect.

**Comment by HerbFargus** [comment]
Sounds good I'm looking forward to seeing what you come up with

**Comment by meleu** [comment]
@HerbFargus I've just added a preliminary, but usable, version of `rpmanager.sh`. I forgot to deal with the root issue, but I'll conclude it tonight. My kids are very zippy now :smile: 
It's intendend to be at `/opt/retropie/supplementary/retropie-manager`.

**Comment by meleu** [comment]
Now I think it's finished!
Take a look here: https://github.com/botolo78/RetroPie-Manager/blob/retropie/rpmanager.sh

**Comment by meleu** [comment]
@HerbFargus 
If the RetroPie-Manager is started by rc.local, it'll be called by root, right?
I solved the root issue thinking only on the sudo (retropie_setup) scenario.
Wait, I'll implement a `--user` option to let the user (with root privileges) choose who will start RetroPie-Manager.

**Comment by botolo78** [comment]
Out of curiosity, why don't use the /etc/profile.d startup sequence?

**Comment by meleu** [comment]
@HerbFargus can you please adapt your installation module to `chown` the `/opt/retropie/supplementary/retropie-manager/` directory tree to the RetroPie user?
Otherwise it'll be problematic to save the log files at `/opt/retropie/supplementary/retropie-manager/logs`.

**Comment by meleu** [comment]
Done! The `rpmanager.sh` is ready to use. The `--user` option has been implemented and now I think it's all done. Please, try it!
https://github.com/botolo78/RetroPie-Manager/blob/retropie/rpmanager.sh

It must be placed at `/opt/retropie/supplementary/retropie-manager/`. @HerbFargus can you please adapt your installation module to put it there?

**Comment by botolo78** [comment]
rpmanager.sh works like a charm :+1:

**Comment by meleu** [comment]
The module was included in RetroPie-Setup, therefore this issue can be closed.
