### ISSUE TITLE
location of files

### ISSUE THREAD

**Issue by meleu** [botolo78/RetroPie-Manager#7]
Hey guys!
Honestly, I don't like to put the RetroPie-Manager directly on my home dir. I think the dir gets poluted with so many directories starting with `RetroPie`. We want to release the RetroPie-Manager to desktop PC users in the future, right? So, I think that filling the home dir with another RetroPie subdir is inelegant.

I would like to propose another place to put the files. What do you guys think about `/opt/retropie/RetroPie-Manager/`?

**Comment by meleu** [comment]
I'm not sure, but I think that doing this way, if the user uninstall RetroPie using `retropie_setup.sh`, the RetroPie-Manager will be deleted as well.
I see it as a benefit. (uninstall RetroPie is a sad thing, though :~( )

**Comment by botolo78** [comment]
I did use the home path just to emulate the RetroPie-Setup name, but I don't have issues in moving the home directory

**Comment by HerbFargus** [comment]
I think with the module I finished it should be fine in `/opt/RetroPie/supplementary/retropie-manager`

I'll submit a PR for the paths so that It will adapt the paths to any user name rather than hardcoding it to user pi (since RetroPie can be run on a pc too)

**Comment by meleu** [comment]
OK. Let's close this issue.
